//PHP的$_POST支援的content-type的型別只有application/x-www-form-urlencoded 或 multipart/form-data 。
POST http://localhost/20211004/1/back/main.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded

h1=4
&w1=7
&r=8
&p=3